refresh_rate: 30 seconds
appenders:
  roll:
    kind: rolling_file
    path: "./logs/backend.log"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: "../logs/backend.{}.log"
        base: 1
        count: 20
root:
  level: info
  appenders:
    - roll
